apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: route53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - dns01:
        route53:
          region: eu-central-1
          hostedZoneID: xxxxx
          accessKeyID: xxxxx
          secretAccessKeySecretRef:
            name: route53
            key: secret-access-key
