kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nginx-load
  namespace: litmus
  creationTimestamp: null
  labels:
    infra_id: 19520541-c8e1-4baf-8b02-ba186f980319
    revision_id: 7b0d679d-adc1-4c1a-82d1-cc4c63825d46
    workflow_id: 227a5ec2-ed81-41bf-a3be-6993c460277f
    workflows.argoproj.io/controller-instanceid: 19520541-c8e1-4baf-8b02-ba186f980319
spec:
  templates:
    - name: nginx-load
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-faults
            template: install-chaos-faults
            arguments: {}
        - - name: k6-loadgen-nl2
            template: k6-loadgen-nl2
            arguments: {}
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
            arguments: {}
    - name: install-chaos-faults
      inputs:
        artifacts:
          - name: k6-loadgen-nl2
            path: /tmp/k6-loadgen-nl2.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Execute the k6 engine using the JS script
                kind: ChaosExperiment

                metadata:
                  name: k6-loadgen
                  labels:
                    name: k6-loadgen
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 3.10.0
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - secrets
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.10.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name k6-loadgen
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "30"
                      - name: CHAOS_INTERVAL
                        value: "30"
                      - name: RAMP_TIME
                        value: "0"
                      - name: SCRIPT_SECRET_NAME
                        value: k6-script
                      - name: SCRIPT_SECRET_KEY
                        value: script.js
                      - name: LIB_IMAGE
                        value: ghcr.io/grafana/k6-operator:latest-runner
                      - name: LIB_IMAGE_PULL_POLICY
                        value: Always
                    labels:
                      name: k6-loadgen
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 3.10.0
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}}
            && sleep 30
        resources: {}
    - name: cleanup-chaos-resources
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:2.11.0
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
    - name: k6-loadgen-nl2
      inputs:
        artifacts:
          - name: k6-loadgen-nl2
            path: /tmp/chaosengine-k6-loadgen-nl2.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    workflow_run_id: "{{ workflow.uid }}"
                    workflow_name: nginx-load
                  annotations:
                    probeRef: '[{"name":"nginx-check","mode":"SOT"}]'
                  generateName: k6-loadgen-nl2
                spec:
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: k6-loadgen
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_INTERVAL
                              value: "30"
                            - name: RAMP_TIME
                              value: "0"
                            - name: SCRIPT_SECRET_NAME
                              value: k6-script
                            - name: SCRIPT_SECRET_KEY
                              value: scripts.js
                            - name: LIB_IMAGE
                              value: ghcr.io/grafana/k6-operator:latest-runner
                            - name: LIB_IMAGE_PULL_POLICY
                              value: Always
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: docker.io/litmuschaos/litmus-checker:2.11.0
        args:
          - -file=/tmp/chaosengine-k6-loadgen-nl2.yaml
          - -saveName=/tmp/engine-name
        resources: {}
  entrypoint: nginx-load
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status:
  startedAt: null
  finishedAt: null
